services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cicd-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cicd-network

networks:
  cicd-network:
    driver: bridge
