name: Deploy Next.js SSR to AWS

on:
  push:
    branches: [GitHub_Actions]
  pull_request:
    branches: [GitHub_Actions]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run linting
        run: npm run lint

      - name: Build Next.js app
        run: npm run build

        

      - name: Create deployment package
        run: |
          zip -r deployment.zip . -x "node_modules/*" ".git/*" "*.md"

      - name: Deploy to EC2 via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "deployment.zip"
          target: "~/"

      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
             sudo apt-get update && sudo apt-get install -y unzip
             cd ~/CI-CD-NEXTJS
             unzip -o ~/deployment.zip
             rm ~/deployment.zip
             docker-compose down
             docker-compose up -d --build
